version: '3'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
    - 80:80
    volumes:
      - ./config/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/blog
  app:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    depends_on:
      - db
    volumes:
    - ./:/var/www/blog
  db:
    image: postgres
    environment:
      POSTGRES_USER: legging
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
    - 5432:5432

volumes:
  postgres-data:
