
##############
# Categories #
##############

CategoryGetAll:
    path: /categories
    methods: ['GET']
    controller: App\Controller\Api\Category\CategoryController
    action: show

##############
#  Comments  #
##############

CommentAddOnPost:
    path: /posts/:slug/comment
    methods: ['GET', 'POST']
    controller: App\Controller\Api\Comment\CommentController
    action: addCommentOnPost
    requirements:
        - slug: '|[^?.A-Z]+$|'
    auth: verified


##############
#   Posts    #
##############

PostGetAll:
    path: /posts
    methods: ['GET']
    controller: App\Controller\Api\Post\PostController
    action: getAllPosts

PostGetAllByCategory:
    path: /posts/category/:name
    methods: ['GET']
    controller: App\Controller\Api\Post\PostController
    action: getAllPostsByCategory
    requirements:
        - name: '|[^?.A-Z]+$|'

PostGetAllByAuthor:
    path: /posts/author/:id
    methods: ['GET']
    controller: App\Controller\Api\Post\PostController
    action: getAllPostsByAuthor
    requirements:
        - id: '|\d+$|'

PostGetSingle:
    path: /posts/:slug
    methods: ['GET']
    controller: App\Controller\Api\Post\PostController
    action: getSinglePost
    requirements:
        - slug: '|[^?.A-Z]+$|'

##############
#   Users    #
##############

UserGetProfile:
    path: /me
    methods: ['GET']
    controller: App\Controller\Api\User\UserController
    action: getProfile
    auth: verified

UserUpdateProfile:
    path: /me/update
    methods: ['GET', 'POST']
    controller: App\Controller\Api\User\UserController
    action: updateProfile
    auth: verified

UserUpdatePassword!:
    path: /me/password/update
    methods: ['GET', 'POST']
    controller: App\Controller\Api\User\UserController
    action: updatePassword
    auth: verified

UserDeleteProfile:
    path: /me/delete
    methods: ['GET']
    controller: App\Controller\Api\User\UserController
    action: deleteProfile
    auth: verified

##############
#   Auth    #
##############

Register:
    path: /register
    methods: ['GET', 'POST']
    controller: App\Controller\Authentication\AuthenticationController
    action: register

Login:
    path: /login
    methods: ['GET', 'POST']
    controller: App\Controller\Authentication\AuthenticationController
    action: login

Logout:
    path: /logout
    methods: ['GET']
    controller: App\Controller\Authentication\AuthenticationController
    action: logout
    auth: verified

##############
#   Home    #
##############

Home:
    path: /
    methods: ['GET']
    controller: App\Controller\Home\HomePageController
    action: index